apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    creator: "${KUBE_USERNAME}"
spec:
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 21600
  backoffLimit: 1
  template:
    metadata:
      labels:
        git-sha: ${GIT_SHA}
        github-event: ${EVENT_NAME}
      annotations:
        sidecar.istio.io/inject: "false"
        creator: "${KUBE_USERNAME}"
    spec:
      nodeSelector:
          mlx.navercorp.com/zone: ${MLXP_ZONE}
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: postfix-state
          emptyDir: {}
        - name: gmail-smtp-relay
          secret:
            secretName: gmail-smtp-relay
      containers:
        # Container definitions are rendered from .github/containers/*.yaml by .github/scripts/render-job-cd.sh.
